# daemon runs in the background
# run something like tail /var/log/zentd/current to see the status
# be sure to run with volumes, ie:
# docker run -v $(pwd)/zentd:/var/lib/zentd -v $(pwd)/wallet:/home/zent --rm -ti zent:latest
FROM ubuntu:16.04

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

ADD https://github.com/just-containers/socklog-overlay/releases/download/v2.1.0-0/socklog-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/socklog-overlay-amd64.tar.gz -C /

COPY . /src/zent


# install build dependencies
# checkout the latest tag
# build and install
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      python-dev \
      gcc-4.9 \
      g++-4.9 \
      git cmake \
      libboost1.58-all-dev && \
    cd /src/zent && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++11" .. && \
    make -j$(nproc) && \
    mkdir -p /usr/local/bin && \
    cp src/Zentd /usr/local/bin/Zentd && \
    cp src/walletd /usr/local/bin/walletd && \
    cp src/zentwallet /usr/local/bin/zentwallet && \
    cp src/miner /usr/local/bin/miner && \
    strip /usr/local/bin/Zentd && \
    strip /usr/local/bin/walletd && \
    strip /usr/local/bin/zentwallet && \
    strip /usr/local/bin/miner && \
    cd / && \
    rm -rf /src/zent && \
    apt-get remove -y build-essential python-dev gcc-4.9 g++-4.9 git cmake libboost1.58-all-dev && \
    apt-get autoremove -y && \
    apt-get install -y  \
      libboost-system1.58.0 \
      libboost-filesystem1.58.0 \
      libboost-thread1.58.0 \
      libboost-date-time1.58.0 \
      libboost-chrono1.58.0 \
      libboost-regex1.58.0 \
      libboost-serialization1.58.0 \
      libboost-program-options1.58.0 \
      libicu55

# setup the zentd service
RUN useradd -r -s /usr/sbin/nologin -m -d /var/lib/zentd zentd && \
    useradd -s /bin/bash -m -d /home/zent zent && \
    mkdir -p /etc/services.d/zentd/log && \
    mkdir -p /var/log/zentd && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/zentd/run && \
    echo "fdmove -c 2 1" >> /etc/services.d/zentd/run && \
    echo "cd /var/lib/zentd" >> /etc/services.d/zentd/run && \
    echo "export HOME /var/lib/zentd" >> /etc/services.d/zentd/run && \
    echo "s6-setuidgid zentd /usr/local/bin/Zentd" >> /etc/services.d/zentd/run && \
    chmod +x /etc/services.d/zentd/run && \
    chown nobody:nogroup /var/log/zentd && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/zentd/log/run && \
    echo "s6-setuidgid nobody" >> /etc/services.d/zentd/log/run && \
    echo "s6-log -bp -- n20 s1000000 /var/log/zentd" >> /etc/services.d/zentd/log/run && \
    chmod +x /etc/services.d/zentd/log/run && \
    echo "/var/lib/zentd true zentd 0644 0755" > /etc/fix-attrs.d/zentd-home && \
    echo "/home/zent true zent 0644 0755" > /etc/fix-attrs.d/zent-home && \
    echo "/var/log/zentd true nobody 0644 0755" > /etc/fix-attrs.d/zentd-logs

VOLUME ["/var/lib/zentd", "/home/zent","/var/log/zentd"]

ENTRYPOINT ["/init"]
CMD ["/usr/bin/execlineb", "-P", "-c", "emptyenv cd /home/zent export HOME /home/zent s6-setuidgid zent /bin/bash"]
